name: Update EPG

on:
  schedule:
    - cron: "0 */6 * * *"   # kas 6 valandas
  workflow_dispatch:        # leid≈æia paleisti ranka

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download latest EPG
        run: |
          curl -L "https://ip-tv.dev/epg/epg.xml.gz" -o epg.xml.gz

      - name: Commit and push
        run: |
          git config --global user.name "giedrius73"
          git config --global user.email "baltasevicius@gmail.com"
          git add epg.xml.gz
          git commit -m "Automatinis EPG atnaujinimas"
          git push
