name: Update EPG

permissions:
  contents: write   # leidžia GITHUB_TOKEN daryti push

on:
  schedule:
    - cron: "0 */6 * * *"   # kas 6 valandas
  workflow_dispatch:        # leidžia paleisti ranka

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Download latest EPG
        run: |
          curl -L "https://ip-tv.dev/epg/epg.xml.gz" -o epg.xml.gz

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          add: "epg.xml.gz"
          message: "Automatinis EPG atnaujinimas"
          author_name: "giedrius73"
          author_email: "baltasevicius@gmail.com"
